### ISSUE TITLE
Not seeing my main.go in the root.

### ISSUE THREAD

**Issue by gedw99** [mjl-/gobuild#2]
This is really useful - thanks for making this.

i guess your hoping people don’t use your server but run their own.

I am trying to build this:

https://github.com/gedw99/sc-make

I am giving  this to web gui:

github.com/gedw99/sc-make
does not see the main.go in the root.

I wo der if the go proxy needs to be told to pull again so that your go build server can see it ?

**Comment by gedw99** [comment]
Here’s the results at 

https://beta.gobuilds.org/github.com/gedw99/sc-make

**Comment by gedw99** [comment]
It’s working 

Was just hard to pick the tin “/“ in the web gui on mobile.

it’s a really awesome service !!

**Comment by mjl-** [comment]
Thanks for giving it a try.
I'm fine with this being used publicly. But I can imagine projects don't want to depend on an external place to provide binaries and want to set up their own.

Good point about the slash. I should probably display the name of the binary as the anchor text instead of the path. Wrote down a todo, may take a while before I get to it.
