### ISSUE TITLE
cgo builds ?

### ISSUE THREAD

**Issue by gedw99** [mjl-/gobuild#4]
https://github.com/gioui/gio-example/blob/main/go.mod

Go can build it but not via the gui. 

<img width="1280" alt="Screenshot 2023-04-15 at 13 26 32" src="https://user-images.githubusercontent.com/53147028/232212150-5bab0f9f-26fd-4ff4-91b3-e53c763a8b44.png">

pick kitchen !!

https://beta.gobuilds.org/gioui.org/example@v0.0.0-20230403133339-059eaf62170b/kitchen/darwin-amd64-go1.20.3/

400 - bad request - preparing build: build does not exist due to cgo dependencies:

gioui.org/internal/gl
gioui.org/gpu/internal/metal
gioui.org/internal/cocoainit
gioui.org/app
gioui.org/gpu/headless

**Comment by mjl-** [comment]
Building cgo programs is currently out of scope for gobuild: it is quite involved to make reproducible binaries for cgo programs (that can be verified externally). You would need the same environment to get the exact same binary, and especially cross-compiling is hard.

As the proverb says: cgo is not go.
Non-cgo programs get the benefit of easily reproducible builds (with gobuild or otherwise). Good reason to not use cgo.

**Comment by gedw99** [comment]
Yep it’s understandable.

I will have to use GitHub actions to build the gioui projects ..
